import {
  Expense,
  Income,
  Goal,
  Category,
  FinancialSummary,
  RecurringTransaction,
  AIInsight,
} from "../types";

export const INITIAL_DEMO_EXPENSES: Expense[] = [
  {
    id: "demo-exp-1",
    user_id: "demo-user",
    amount: 85000,
    currency: "CRC",
    description: "Supermercado Automercado",
    category: "Alimentación",
    date: new Date(Date.now() - 1 * 86400000).toISOString(),
    payment_method: "Tarjeta de Débito",
  },
  {
    id: "demo-exp-2",
    user_id: "demo-user",
    amount: 32000,
    currency: "CRC",
    description: "Gasolina y Lavado Auto",
    category: "Transporte",
    date: new Date(Date.now() - 3 * 86400000).toISOString(),
    payment_method: "Tarjeta de Crédito",
  },
  {
    id: "demo-exp-3",
    user_id: "demo-user",
    amount: 28500,
    currency: "CRC",
    description: "Recibo CNFL Electricidad",
    category: "Servicios",
    date: new Date(Date.now() - 5 * 86400000).toISOString(),
    payment_method: "Transferencia",
  },
  {
    id: "demo-exp-4",
    user_id: "demo-user",
    amount: 45000,
    currency: "CRC",
    description: "Cena Restaurante con Amigos",
    category: "Entretenimiento",
    date: new Date(Date.now() - 6 * 86400000).toISOString(),
    payment_method: "Efectivo",
  },
  {
    id: "demo-exp-5",
    user_id: "demo-user",
    amount: 35000,
    currency: "CRC",
    description: "Consulta Dental y Farmacia",
    category: "Salud",
    date: new Date(Date.now() - 8 * 86400000).toISOString(),
    payment_method: "Tarjeta de Débito",
  },
  {
    id: "demo-exp-6",
    user_id: "demo-user",
    amount: 250000,
    currency: "CRC",
    description: "Alquiler Apartamento Mensual",
    category: "Vivienda",
    date: new Date(Date.now() - 12 * 86400000).toISOString(),
    payment_method: "Transferencia",
  },
];

export const INITIAL_DEMO_INCOMES: Income[] = [
  {
    id: "demo-inc-1",
    user_id: "demo-user",
    amount: 650000,
    currency: "CRC",
    source: "Salario Empresa Tech",
    category: "Salario",
    date: new Date(Date.now() - 4 * 86400000).toISOString(),
    payment_method: "Transferencia",
  },
  {
    id: "demo-inc-2",
    user_id: "demo-user",
    amount: 200000,
    currency: "CRC",
    source: "Proyecto Freelance UI/UX",
    category: "Freelance",
    date: new Date(Date.now() - 9 * 86400000).toISOString(),
    payment_method: "Sinpe Móvil",
  },
  {
    id: "demo-inc-3",
    user_id: "demo-user",
    amount: 100000,
    currency: "CRC",
    source: "Rendimientos Inversión CDP",
    category: "Inversiones",
    date: new Date(Date.now() - 14 * 86400000).toISOString(),
    payment_method: "Transferencia",
  },
];

export const INITIAL_DEMO_GOALS: Goal[] = [
  {
    id: "demo-goal-1",
    user_id: "demo-user",
    title: "Fondo de Emergencia (6 meses)",
    target_amount: 1500000,
    current_amount: 1050000,
    currency: "CRC",
    deadline: "2026-12-31",
    category: "Emergencia",
  },
  {
    id: "demo-goal-2",
    user_id: "demo-user",
    title: "Vacaciones a Japón",
    target_amount: 2000000,
    current_amount: 720000,
    currency: "CRC",
    deadline: "2027-04-15",
    category: "Viajes",
  },
  {
    id: "demo-goal-3",
    user_id: "demo-user",
    title: "Laptop Profesional M3",
    target_amount: 1200000,
    current_amount: 1200000,
    currency: "CRC",
    deadline: "2026-10-30",
    category: "Inversión",
  },
  {
    id: "demo-goal-4",
    user_id: "demo-user",
    title: "Prima para Casa Propia",
    target_amount: 8000000,
    current_amount: 2400000,
    currency: "CRC",
    deadline: "2028-12-31",
    category: "Vivienda",
  },
];

export const INITIAL_DEMO_RECURRING: RecurringTransaction[] = [
  {
    id: "demo-rec-1",
    user_id: "demo-user",
    amount: 250000,
    currency: "CRC",
    description: "Alquiler Apartamento",
    category: "Vivienda",
    frequency: "monthly",
    start_date: "2026-01-01",
    next_due_date: new Date(Date.now() + 5 * 86400000).toISOString().split("T")[0],
    is_active: true,
    payment_method: "Transferencia",
  },
  {
    id: "demo-rec-2",
    user_id: "demo-user",
    amount: 16500,
    currency: "CRC",
    description: "Netflix + Spotify Familiar",
    category: "Entretenimiento",
    frequency: "monthly",
    start_date: "2026-01-15",
    next_due_date: new Date(Date.now() + 10 * 86400000).toISOString().split("T")[0],
    is_active: true,
    payment_method: "Tarjeta",
  },
  {
    id: "demo-rec-3",
    user_id: "demo-user",
    amount: 650000,
    currency: "CRC",
    description: "Salario Quincenal Tech",
    category: "Salario",
    frequency: "biweekly",
    start_date: "2026-01-15",
    next_due_date: new Date(Date.now() + 12 * 86400000).toISOString().split("T")[0],
    is_active: true,
    payment_method: "Transferencia",
  },
  {
    id: "demo-rec-4",
    user_id: "demo-user",
    amount: 22000,
    currency: "CRC",
    description: "Membresía Gimnasio SmartFit",
    category: "Salud",
    frequency: "monthly",
    start_date: "2026-02-01",
    next_due_date: new Date(Date.now() + 2 * 86400000).toISOString().split("T")[0],
    is_active: true,
    payment_method: "Tarjeta",
  },
];

export const INITIAL_DEMO_CATEGORIES: Category[] = [
  {
    id: "cat-1",
    name: "Alimentación",
    icon: "utensils",
    color: "#f59e0b",
    type: "expense",
    is_default: true,
  },
  {
    id: "cat-2",
    name: "Transporte",
    icon: "car",
    color: "#3b82f6",
    type: "expense",
    is_default: true,
  },
  {
    id: "cat-3",
    name: "Servicios",
    icon: "zap",
    color: "#8b5cf6",
    type: "expense",
    is_default: true,
  },
  {
    id: "cat-4",
    name: "Entretenimiento",
    icon: "film",
    color: "#ec4899",
    type: "expense",
    is_default: true,
  },
  {
    id: "cat-5",
    name: "Salud",
    icon: "heart",
    color: "#10b981",
    type: "expense",
    is_default: true,
  },
  {
    id: "cat-6",
    name: "Vivienda",
    icon: "home",
    color: "#06b6d4",
    type: "expense",
    is_default: true,
  },
  {
    id: "cat-7",
    name: "Salario",
    icon: "briefcase",
    color: "#10b981",
    type: "income",
    is_default: true,
  },
  {
    id: "cat-8",
    name: "Freelance",
    icon: "laptop",
    color: "#3b82f6",
    type: "income",
    is_default: true,
  },
  {
    id: "cat-9",
    name: "Inversiones",
    icon: "trending-up",
    color: "#f59e0b",
    type: "income",
    is_default: true,
  },
  {
    id: "cat-custom-1",
    name: "Gimnasio y Bienestar",
    icon: "activity",
    color: "#8b5cf6",
    type: "expense",
    is_default: false,
  },
];

export const INITIAL_DEMO_AI_INSIGHTS: AIInsight[] = [
  {
    type: "savings",
    title: "Tasa de Ahorro Saludable",
    desc: "Tu tasa de ahorro del 49.2% supera con creces la meta estándar del 20%. Mantén este ritmo para acelerar tus metas.",
    priority: "high",
  },
  {
    type: "goal",
    title: "Meta Cumplida: Laptop M3",
    desc: "Has alcanzado el 100% de tu objetivo para la laptop. Puedes redirigir ese flujo de ahorro hacia tu Fondo de Emergencia.",
    priority: "medium",
  },
  {
    type: "optimization",
    title: "Compromiso Fijo Próximo",
    desc: "El pago de membresía de gimnasio (₡22,000) vence en 2 días. Tu liquidez actual cubre cómodamente este egreso.",
    priority: "low",
  },
];
